# Generated by Django 6.0 on 2025-12-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='page',
        ),
    ]
