# Generated by Django 6.0 on 2025-12-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingApp', '0002_player_delete_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
