# Generated by Django 6.0 on 2025-12-23 21:42

from django.db import migrations

USER_START = 10000
class Migration(migrations.Migration):

    dependencies = [
        ('ratingApp', '0004_login_info_reviews_delete_player'),
    ]

    operations = [
        migrations.RunSQL(
            f"ALTER TABLE auth_user AUTO_INCREMENT = {USER_START};"
        ),
    ]
