# Generated by Django 6.0 on 2025-12-25 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingApp', '0005_auto_20251223_1342'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login_info',
            name='password',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='publish_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
