# Generated by Django 6.0 on 2025-12-25 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratingApp', '0006_reviews_user_alter_login_info_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
    ]
