# Generated by Django 6.0 on 2026-01-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingApp', '0012_alter_reviews_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_info',
        ),
        migrations.AddField(
            model_name='reviews',
            name='movie_ids',
            field=models.CharField(default='movie', max_length=50),
            preserve_default=False,
        ),
    ]
