# Generated by Django 6.0 on 2026-01-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingApp', '0013_delete_login_info_reviews_movie_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
